# -*- coding: utf-8 -*-
"""Model_Train_Crop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csmw_wd36OVRjbl5Z9auWbEubdgJIDsa
"""
import pickle
import pandas as pd
import numpy as np

df=pd.read_csv("Crop_recommendation.csv")

df

df.isnull().sum()

df.describe()

df.info()

from sklearn.preprocessing import LabelEncoder
oc=LabelEncoder()
df['season']=oc.fit_transform(df[['season']])

x=df.iloc[:,:-1]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,y_train)

pred=model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,pred)
print(accuracy)

pickle.dump(model,open("model.pkl","wb"))